version: '2'
services:
  jenkins:
    image: 'jenkins/jenkins:latest'
    container_name: jenkins
    user: root
    privileged: true
    ports:
#      - '80:8080'
      - '443:8083'
      - '50000:50000'
    extra_hosts:
      - "gitlab.devops.co.th:10.140.0.3"
    volumes:
      - '/root/jenkins/jenkins_data:/var/jenkins_home'
    environment:
      JENKINS_OPTS: --httpPort=-1 --httpsPort=8083 --httpsCertificate=/var/jenkins_home/jenkins_cert.pem --httpsPrivateKey=/var/jenkins_home/jenkins.pem 
